# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf3f6d795819cb6311bb83a4abe0a39368c4b6bdebc22c1985d0aa0617b3c9181de159e1a21e0880bcb7276410f054c11bddbb01bc7e9cc790dbca3c324a2412

test:
  secret_key_base: ff27dfe1126422d69dfd2405fb0a8f5c897dcf1d487d0abd28644adf05cabb7cb1a034cdb496b1b43d47518d830877a3ea2184bfa10aec14bb4d901ffdb4c951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
